Revised version based on change requests.
Signed-off-by: Dennis Huang <haicha.tw@gmail.com>

diff --git a/install/primehub-support b/install/primehub-support
--- a/install/primehub-support
+++ b/install/primehub-support
@@ -1,9 +1,13 @@
 #!/bin/bash
 # InfuseAI support data collection script
-HOME=$HOME
-LOG_DIR=$HOME/infuseai_support_logs_$(date +'%Y%m%d%H%M')
+# Author : Dennis Huang
+# Version : 2022/10/12 Version 2
+HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+ARCHIVE_DIR=$HOME/infuseai_support
+LOG_DIR=$HOME/infuseai_support/infuseai_support_logs_$(date +'%Y%m%d%H%M')
 TIMESTAMP=$(date +%F-%H-%M-%S)
 
+START() {
 echo ""
 printf "\E[5;30;47m#################################################################\E[0m\n"
 printf "\E[5;30;47m#                                                               #\E[0m\n"
@@ -11,6 +15,17 @@ printf "\E[5;30;47m#    Start running InfuseAI support data collection script.  
 printf "\E[5;30;47m#                                                               #\E[0m\n"
 printf "\E[5;30;47m#################################################################\E[0m\n"
 echo ""
+}
+
+END() {
+echo ""
+printf "\E[0;90;102m#################################################################\E[0m\n"
+printf "\E[0;90;102m#                                                               #\E[0m\n"
+printf "\E[0;90;102m#  InfuseAI support data collection is completed successfully!  #\E[0m\n"
+printf "\E[0;90;102m#                                                               #\E[0m\n"
+printf "\E[0;90;102m#################################################################\E[0m\n"
+echo ""
+}
 
 if [ ! "$BASH_VERSION" ] ; then
 	echo "-------------------------------------------------------------------------"
@@ -28,32 +43,7 @@ set -o pipefail
 
 #=========================================================================#
 
-# Color block function
-info() {
-  echo -e "\033[0;32m$1\033[0m"
-}
-
-warn() {
-  echo -e "\033[0;93m$1\033[0m"
-}
-
-error() {
-  echo -e "\033[0;91m$1\033[0m" >&2
-}
-
-highlight() {
-  echo -e "\033[1;96m$1\033[0m"
-}
-
-mark() {
-  echo -e "\033[0;97m$1\033[0m"
-}
-
-notpresent() {
-  echo -e "\033[0;31m$1\033[0m"
-}
-
-#=========================================================================#
+START
 
 # Check host type
 OSTYPE=$(echo $OSTYPE)
@@ -69,7 +59,7 @@ else
 fi
 echo ""
 
-# Check if this scrip run by root-like account
+# Check if this script run by root-like account
 USER_UID=$(echo $UID)
 USER_NAME=$(echo $USER)
 SUDO=$(groups $USER_NAME | grep -qo sudo ; echo $?)
@@ -119,15 +109,16 @@ echo ""
 
 # Check system date and time.
 TIME=$(date +%Y/%m/%d-%H:%M:%S)
+ANSIBLE_CHECK=$(command -v ansible)
 echo "-------------------------------------------------------------------------"
 echo "Check system date and time."
-if [[ "$(command -v ansible)" != "" ]]; then
+if [[ $ANSIBLE_CHECK != "" ]]; then
 	read -p "Please input your inventory file full path, skip this step by pressing enter. (e.g. $HOME/.ansible/inventory.yaml) > " inventory_file
-	if [[ $inventory_file == "" ]]; then
-		echo "Will not run ansible command due to empty input."
-	else
+	if [[ -f $inventory_file ]]; then
 		ansible -i $inventory_file all -m shell -a 'date' -f99 &> $LOG_DIR/ansible_date_$TIMESTAMP.log
 		echo "System date log is now logged at $LOG_DIR/ansible_date_$TIMESTAMP.log"
+	else
+		echo "Will not run ansible command due to empty input or non-existent file."
 	fi
 else
 	echo "Ansible command not found, skipping....."
@@ -138,41 +129,7 @@ echo $TIME
 echo "-------------------------------------------------------------------------"
 echo ""
 
-# Check system k8s service
-CHECK_KUBELET=$(systemctl -la | grep -o kubelet.service 1> /dev/null 2>&1 ; echo $?)
-CHECK_RKE=$(docker ps -a 2> /dev/null | grep -o kubelet 1> /dev/null 2>&1 ; echo $?)
-echo "-------------------------------------------------------------------------"
-if [[ "$(command -v docker)" == "" ]]; then
-	echo "Docker command not found, skipping....."
-else
-	echo "Docker installed, moving to next step."
-	if [[ $CHECK_KUBELET -eq 0 && $CHECK_RKE -eq 1 ]]; then
-		echo "This host has Kubelet service installed."
-		K8S_TYPE=KUBELET
-	elif [[ $CHECK_KUBELET -eq 1 && $CHECK_RKE -eq 0 ]]; then
-		echo "This host has RKE service installed."
-		K8S_TYPE=RKE
-	else
-		echo "Cannot detect k8s service on this host, exit."
-		exit 1
-	fi
-fi
-
-if [[ $K8S_TYPE == "RKE" ]]; then
-	echo ""
-	echo "Dump kubelet logs to $LOG_DIR"
-	docker logs kubelet --tail 1000 &> $LOG_DIR/kubelet_service_$TIMESTAMP.log
-	echo "Kubelet service log is now logged at $LOG_DIR/kubelet_service_$TIMESTAMP.log"
-elif [[ $K8S_TYPE == "KUBELET" ]]; then
-	echo ""
-	echo "Dump kubelet logs to $LOG_DIR"
-	systemctl status kubelet.service -l &> $LOG_DIR/kubelet_status_$TIMESTAMP.log
-	journalctl -u kubelet.service -n 1000 &> $LOG_DIR/kubelet_service_$TIMESTAMP.log
-	echo "Kubelet status log is now logged at $LOG_DIR/kubelet_status_$TIMESTAMP.log"
-	echo "Kubelet service log is now logged at $LOG_DIR/kubelet_service_$TIMESTAMP.log"
-fi
-echo "-------------------------------------------------------------------------"
-echo ""
+#=========================================================================#
 
 # Check system resources usage and NVIDIA driver status
 SYS_CHECK() {
@@ -215,31 +172,6 @@ else
 	echo "System disk usage is now logged at $LOG_DIR/disk_usage_$TIMESTAMP.log"
 	echo "System partition table is now logged at $LOG_DIR/part_table_$TIMESTAMP.log"
 fi
-}
-
-echo "-------------------------------------------------------------------------"
-echo "Check system resources usage and NVIDIA driver status....."
-if [[ "$(command -v ansible)" != "" ]]; then
-	if [[ $inventory_file == "" ]]; then
-		echo "Will not run ansible command due to empty input."
-		SYS_CHECK
-	else
-		ansible -i $inventory_file all -m shell -a 'nvidia-smi' -f99 &> $LOG_DIR/ansible_nvidia_driver_$TIMESTAMP.log
-		ansible -i $inventory_file all -m shell -a 'mpstat -P ALL' -f99 &> $LOG_DIR/ansible_cpu_$TIMESTAMP.log
-		ansible -i $inventory_file all -m shell -a 'free -g' -f99 &> $LOG_DIR/ansible_mem_$TIMESTAMP.log
-		ansible -i $inventory_file all -m shell -a 'df -h' -f99 &> $LOG_DIR/ansible_disk_$TIMESTAMP.log
-		ansible -i $inventory_file all -m shell -a 'lsblk' -f99 &> $LOG_DIR/ansible_part_$TIMESTAMP.log
-		echo "System NVIDIA driver status is now logged at $LOG_DIR/ansible_nvidia_driver_$TIMESTAMP.log"
-		echo "System cpu usage is now logged at $LOG_DIR/ansible_cpu_$TIMESTAMP.log"
-		echo "System memory usage is now logged at $LOG_DIR/ansible_mem_$TIMESTAMP.log"
-		echo "System disk usage is now logged at $LOG_DIR/ansible_disk_$TIMESTAMP.log"
-		echo "System partition table is now logged at $LOG_DIR/ansible_part_$TIMESTAMP.log"
-	fi
-else
-	echo "Ansible command not found, skipping....."
-	echo ""
-	SYS_CHECK
-fi
 echo ""
 
 echo "Dump system logs to $LOG_DIR"
@@ -249,6 +181,122 @@ echo "System log is now logged at $LOG_DIR/dmesg_$TIMESTAMP.log"
 echo "Mountpoint log is now logged at $LOG_DIR/mount_$TIMESTAMP.log"
 echo "-------------------------------------------------------------------------"
 echo ""
+}
+
+ANS_SYS_CHECK() {
+
+echo "Log NVIDIA driver status to $LOG_DIR"
+if [[ "$(command -v nvidia-smi)" == "" ]]; then
+	echo "nvidia-smi command not found, skipping....."
+else
+	echo "nvidia-smi command installed, capture current nvidia device status."
+	ansible -i $inventory_file all -m shell -a 'nvidia-smi' -f99 &> $LOG_DIR/ansible_nvidia_driver_$TIMESTAMP.log
+	echo "System NVIDIA driver status is now logged at $LOG_DIR/ansible_nvidia_driver_$TIMESTAMP.log"
+fi
+echo ""
+
+echo "Log system cpu usage usage to $LOG_DIR"
+if [[ "$(command -v mpstat)" == "" ]]; then
+	echo "mpstat command not found, skipping....."
+else
+	echo "mpstat command installed, capture current system cpu usage."
+	ansible -i $inventory_file all -m shell -a 'mpstat -P ALL' -f99 &> $LOG_DIR/ansible_cpu_$TIMESTAMP.log
+	echo "System cpu usage is now logged at $LOG_DIR/ansible_cpu_$TIMESTAMP.log"
+fi
+echo ""
+
+echo "Log system memory usage usage to $LOG_DIR"
+if [[ "$(command -v free)" == "" ]]; then
+	echo "free command not found, skipping....."
+else
+	echo "free command installed, capture current system memory usage."
+	ansible -i $inventory_file all -m shell -a 'free -g' -f99 &> $LOG_DIR/ansible_mem_$TIMESTAMP.log
+	echo "System memory usage is now logged at $LOG_DIR/ansible_mem_$TIMESTAMP.log"
+fi
+echo ""
+
+echo "Log system disk usage to $LOG_DIR"
+if [[ "$(command -v df)" == "" && "$(command -v lsblk)" == "" ]]; then
+	echo "df and lsblk command not found, skipping....."
+else
+	echo "df and lsblk command installed, capture current system disk usage and partition table."
+	ansible -i $inventory_file all -m shell -a 'df -h' -f99 &> $LOG_DIR/ansible_disk_$TIMESTAMP.log
+	ansible -i $inventory_file all -m shell -a 'lsblk' -f99 &> $LOG_DIR/ansible_part_$TIMESTAMP.log
+	echo "System disk usage is now logged at $LOG_DIR/ansible_disk_$TIMESTAMP.log"
+	echo "System partition table is now logged at $LOG_DIR/ansible_part_$TIMESTAMP.log"
+fi
+echo ""
+
+echo "Dump system logs to $LOG_DIR"
+ansible -i $inventory_file all -m shell -a 'dmesg -T | tail -1000' -b -f99 &> $LOG_DIR/ansible_dmesg_$TIMESTAMP.log
+ansible -i $inventory_file all -m shell -a 'mount' -f99 &> $LOG_DIR/ansible_mount_$TIMESTAMP.log
+echo "System log is now logged at $LOG_DIR/ansible_dmesg_$TIMESTAMP.log"
+echo "Mountpoint log is now logged at $LOG_DIR/ansible_mount_$TIMESTAMP.log"
+echo "-------------------------------------------------------------------------"
+echo ""
+}
+
+echo "-------------------------------------------------------------------------"
+echo "Check system resources usage and NVIDIA driver status....."
+if [[ $ANSIBLE_CHECK != "" ]]; then
+	if [[ ! -f $inventory_file ]]; then
+		echo ""
+		echo "Will not run ansible command due to empty input or non-existent file."
+		echo ""
+		SYS_CHECK
+	else
+		echo ""
+		ANS_SYS_CHECK
+	fi
+else
+	echo "Ansible command not found, skipping....."
+	echo ""
+	SYS_CHECK
+fi
+
+#=========================================================================#
+
+# Check system k8s service
+K8S() {
+CHECK_KUBELET=$(systemctl -la | grep -o kubelet.service 1> /dev/null 2>&1 ; echo $?)
+CHECK_RKE=$(docker ps -a 2> /dev/null | grep -o kubelet 1> /dev/null 2>&1 ; echo $?)
+CHECK_KUBELET_SERVICE=$(systemctl is-active kubelet.service)
+CHECK_DOCKER_SERVICE=$(systemctl is-active docker.service)
+echo "-------------------------------------------------------------------------"
+if [[ "$(command -v docker)" != "" && $CHECK_DOCKER_SERVICE == "active" ]]; then
+	echo "Docker installed, moving to next step."
+	if [[ $CHECK_KUBELET -eq 0 && $CHECK_RKE -eq 1 ]]; then
+		echo "This host has Kubelet service installed."
+		K8S_TYPE=KUBELET
+	elif [[ $CHECK_KUBELET -eq 1 && $CHECK_RKE -eq 0 ]]; then
+		echo "This host has RKE service installed."
+		K8S_TYPE=RKE
+	else
+		echo "Cannot detect k8s service on this host, exit."
+		exit 1
+	fi
+else
+	echo "Docker command not found, skipping....."
+fi
+
+if [[ $K8S_TYPE == "RKE" ]]; then
+	echo ""
+	echo "Dump kubelet logs to $LOG_DIR"
+	docker logs kubelet --tail 1000 &> $LOG_DIR/kubelet_service_$TIMESTAMP.log
+	echo "Kubelet service log is now logged at $LOG_DIR/kubelet_service_$TIMESTAMP.log"
+elif [[ $K8S_TYPE == "KUBELET"  && $CHECK_KUBELET_SERVICE == "active" ]]; then
+	echo ""
+	echo "Dump kubelet logs to $LOG_DIR"
+	systemctl status kubelet.service -l &> $LOG_DIR/kubelet_status_$TIMESTAMP.log
+	journalctl -u kubelet.service -n 1000 &> $LOG_DIR/kubelet_service_$TIMESTAMP.log
+	echo "Kubelet status log is now logged at $LOG_DIR/kubelet_status_$TIMESTAMP.log"
+	echo "Kubelet service log is now logged at $LOG_DIR/kubelet_service_$TIMESTAMP.log"
+fi
+echo "-------------------------------------------------------------------------"
+echo ""
+}
+
+K8S
 
 #=========================================================================#
 
@@ -301,7 +349,7 @@ if [[ $NOT_RUNNING_POD == "" ]]; then
 	echo "No pod is in "not ready" status, skipping....."
 else
 	echo "Not ready pod found, list pod status."
-	$NOT_RUNNING_POD &> $LOG_DIR/kubernetes_not_ready_pod_$TIMESTAMP.log
+	echo $NOT_RUNNING_POD &> $LOG_DIR/kubernetes_not_ready_pod_$TIMESTAMP.log
 	echo "Kubernetes NotReady pod status log is now logged at $LOG_DIR/kubernetes_not_ready_pod_$TIMESTAMP.log"
 fi
 echo ""
@@ -311,7 +359,7 @@ if [[ $NOT_READY_DEPLOY == "" ]]; then
 	echo "No deployment is unavailable, skipping....."
 else
 	echo "Unavailable deployment found, list deployment status."
-	$NOT_READY_DEPLOY &> $LOG_DIR/kubernetes_unavailable_deploy_$TIMESTAMP.log
+	echo $NOT_READY_DEPLOY &> $LOG_DIR/kubernetes_unavailable_deploy_$TIMESTAMP.log
 	echo "Kubernetes NotReady pod status log is now logged at $LOG_DIR/kubernetes_unavailable_deploy_$TIMESTAMP.log"
 fi
 echo "-------------------------------------------------------------------------"
@@ -358,15 +406,18 @@ if [[ "$(command -v kubectl-primehub)" == "" ]]; then
 else
 	echo "Kubectl-primehub installed, Check PrimeHub status."
 	kubectl primehub version &> $LOG_DIR/primehub_version_$TIMESTAMP.log
-	#Command usage: kubectl primehub [notebook|job|gitsync|nfs|image-builder|deploy|system] 
+	#Command usage: kubectl primehub [notebook|job|gitsync|nfs|image-builder|deploy|system]
 	kubectl primehub notebook &> $LOG_DIR/primehub_notebook_$TIMESTAMP.log
 	kubectl primehub job &> $LOG_DIR/primehub_job_$TIMESTAMP.log
 	kubectl primehub nfs &> $LOG_DIR/primehub_nfs_$TIMESTAMP.log
 	kubectl primehub deploy &> $LOG_DIR/primehub_deploy_$TIMESTAMP.log
 	kubectl primehub system &> $LOG_DIR/primehub_system_$TIMESTAMP.log
+	echo "Collect PrimeHub diagnostic logs, please wait....."
 	cd $LOG_DIR
-	kubectl primehub diagnose --path $HOME
+	kubectl primehub diagnose --path $LOG_DIR
+	echo "Done."
 	cd $HOME
+	echo ""
 	echo "PrimeHub version log is now logged at $LOG_DIR/primehub_version_$TIMESTAMP.log"
 	echo "PrimeHub notebook list is now logged at $LOG_DIR/primehub_notebook_$TIMESTAMP.log"
 	echo "PrimeHub job list is now logged at $LOG_DIR/primehub_job_$TIMESTAMP.log"
@@ -385,7 +436,7 @@ FILE_NAME="infuseai-support-log-$(date +'%Y%m%d%H%M')"
 echo "-------------------------------------------------------------------------"
 echo "Compressing logs....."
 cd $LOG_DIR
-tar czf $HOME/$FILE_NAME.tgz * 1> /dev/null 2>&1
+tar czf $ARCHIVE_DIR/$FILE_NAME.tgz * 1> /dev/null 2>&1
 cd $HOME
 echo "Done."
 echo "-------------------------------------------------------------------------"
@@ -393,15 +444,10 @@ echo ""
 
 echo "-------------------------------------------------------------------------"
 echo "Logs folder: $LOG_DIR"
-echo "Log archive: $(realpath $HOME/$FILE_NAME.tgz)"
+echo "Log archive: $(realpath $ARCHIVE_DIR/$FILE_NAME.tgz)"
 echo "Please send the log archive to support engineer for further analysis."
 echo "-------------------------------------------------------------------------"
 
-echo ""
-printf "\E[0;90;102m#################################################################\E[0m\n"
-printf "\E[0;90;102m#                                                               #\E[0m\n"
-printf "\E[0;90;102m#  InfuseAI support data collection is completed successfully!  #\E[0m\n"
-printf "\E[0;90;102m#                                                               #\E[0m\n"
-printf "\E[0;90;102m#################################################################\E[0m\n"
-echo ""
+END
+
 exit 0
