[Feature] ch17428 Update primehub-install script to support singlenode
Signed-off-by: Kent Huang <kentwelcome@gmail.com>

diff --git a/install/primehub-install b/install/primehub-install
--- a/install/primehub-install
+++ b/install/primehub-install
@@ -15,6 +15,8 @@ YQ_VERSION=2.1.2
 INSECURE_REGISTRY=''
 CONTAINER_REGISTRY=''
 
+PRIMEHUB_REPO="https://github.com/InfuseAI/primehub.git"
+PRIMEHUB_TARBALL="https://github.com/InfuseAI/primehub/archive/refs/heads/master.tar.gz"
 PRIMEHUB_HELM_CHART="https://charts.infuseai.io/index.yaml"
 SUPPORT_K8S_VERSION="1.15 1.16 1.17 1.18 1.19 1.20"
 K8S_VERSION=1.17
@@ -54,6 +56,15 @@ error() {
 primehub_config_path() {
   local CONFIG_PATH=~/.primehub/config/$(kubectl config current-context)
   echo "${CONFIG_PATH}"
+}
+
+primehub_repo_path() {
+  if [ -d helmfiles ]; then
+    echo "$(realpath $DIR/../)"
+  else
+    local REPO_PATH=~/.primehub/src/primehub
+    echo "${REPO_PATH}"
+  fi
 }
 
 prepare_env_varible() {
@@ -215,6 +226,28 @@ check_primehub_required_bin() {
     return 0
   fi
   return -1
+}
+
+check_primehub_repo() {
+  local PRIMEHUB_REPO_PATH=$(primehub_repo_path)
+  if [ ! -d $PRIMEHUB_REPO_PATH ]; then
+    warn "[Not Found] PrimeHub repo"
+    download::primehub_repo
+  fi
+}
+
+download::primehub_repo() {
+  mkdir -p ~/.primehub/src/primehub
+  if command -v git > /dev/null; then
+    info "[Clone] PrimeHub repo ..."
+    git clone $PRIMEHUB_REPO ~/.primehub/src/primehub
+  else
+    info "[Download] PrimeHub repo ..."
+    curl -L $PRIMEHUB_TARBALL -o ~/.primehub/src/master.tar.gz
+    tar zxf ~/.primehub/src/master.tar.gz -C ~/.primehub/src
+    mv ~/.primehub/src/primehub-master/* ~/.primehub/src/primehub
+    rm -rf ~/.primehub/src/master.tar.gz ~/.primehub/src/primehub-master
+  fi
 }
 
 install:kubectl() {
@@ -759,8 +792,12 @@ generate::keycloak_grafana_client() {
 }
 
 install::prometheus() {
+  local PRIMEHUB_REPO_PATH=$(primehub_repo_path)
+  local HELMFIEL_PATH=${PRIMEHUB_REPO_PATH}/install/helmfiles
   local PROMETHEUS_CONFIG=$(primehub_config_path)/helm_override/prometheus.yaml
   local PRIMEHUB_GRAFANA_DASHBOARD_BASIC_CONFIG=$(primehub_config_path)/helm_override/primehub-grafana-dashboard-basic.yaml
+
+  check_primehub_repo
 
   # Prometheus Chart
   if [ ! -f "${PROMETHEUS_CONFIG}" ]; then
@@ -772,7 +809,7 @@ install::prometheus() {
   fi
 
   info "[Install] Prometheus"
-  helmfile -f ${DIR}/helmfiles/prometheus-operator sync
+  helmfile -f ${HELMFIEL_PATH}/prometheus-operator sync
 
   # PrimeHub Grafana Dashboard Chart
   if [ ! -f "${PRIMEHUB_GRAFANA_DASHBOARD_BASIC_CONFIG}" ]; then
@@ -784,15 +821,19 @@ install::prometheus() {
   fi
 
   info "[Install] PrimeHub Grafana Dashboard Basic"
-  helmfile -f ${DIR}/helmfiles/primehub-grafana-dashboard-basic sync
+  helmfile -f ${HELMFIEL_PATH}/primehub-grafana-dashboard-basic sync
 }
 
 diff::prometheus() {
+  local PRIMEHUB_REPO_PATH=$(primehub_repo_path)
+  local HELMFIEL_PATH=${PRIMEHUB_REPO_PATH}/install/helmfiles
   local PROMETHEUS_CONFIG=$(primehub_config_path)/helm_override/prometheus.yaml
   local PRIMEHUB_GRAFANA_DASHBOARD_BASIC_CONFIG=$(primehub_config_path)/helm_override/primehub-grafana-dashboard-basic.yaml
 
-  helmfile -f ${DIR}/helmfiles/prometheus-operator diff --context 2 --skip-deps --args '--disable-validation'
-  helmfile -f ${DIR}/helmfiles/primehub-grafana-dashboard-basic diff --context 2 --skip-deps --args '--disable-validation'
+  check_primehub_repo
+
+  helmfile -f ${HELMFIEL_PATH}/prometheus-operator diff --context 2 --skip-deps --args '--disable-validation'
+  helmfile -f ${HELMFIEL_PATH}/primehub-grafana-dashboard-basic diff --context 2 --skip-deps --args '--disable-validation'
 }
 
 destroy::prometheus() {
@@ -865,6 +906,10 @@ diff::singlenode() {
 }
 
 diff::primehub() {
+  local PRIMEHUB_REPO_PATH=$(primehub_repo_path)
+  local HELMFIEL_PATH=${PRIMEHUB_REPO_PATH}/install/helmfiles
+  check_primehub_repo
+
   info "[Check] primehub.yaml"
   export RELEASE_NAMESPACE=${PRIMEHUB_NAMESPACE}
   if [[ "${PRIMEHUB_CHART_PATH}" != "" ]]; then
@@ -872,7 +917,7 @@ diff::primehub() {
   else
     export CHART_VERSION=${PRIMEHUB_VERSION}
   fi
-  helmfile -f ${DIR}/helmfiles/primehub diff --context 2 --skip-deps --args '--disable-validation'
+  helmfile -f ${HELMFIEL_PATH}/primehub diff --context 2 --skip-deps --args '--disable-validation'
 }
 
 error_log_primehub() {
@@ -884,7 +929,7 @@ error_log_primehub() {
 
 progress_primehub() {
   sleep 10
-  until kubectl -n ${PRIMEHUB_NAMESPACE} get job/primehub-bootstrap > /dev/null 2&>1; do
+  until kubectl -n ${PRIMEHUB_NAMESPACE} get job primehub-bootstrap > /dev/null 2> /dev/null; do
     sleep 2;
   done
   if kubectl -n ${PRIMEHUB_NAMESPACE} get sts/keycloak > /dev/null 2>&1 ; then
@@ -903,15 +948,19 @@ progress_primehub() {
 
 install::primehub() {
   local PRIMEHUB_CONFIG=$(primehub_config_path)/helm_override/primehub.yaml
+  local PRIMEHUB_REPO_PATH=$(primehub_repo_path)
+  local HELMFIEL_PATH=${PRIMEHUB_REPO_PATH}/install/helmfiles
   info "[Check] primehub.yaml"
+
+  check_primehub_repo
 
   if [ ! -f "${PRIMEHUB_CONFIG}" ]; then
     mkdir -p $(primehub_config_path)/helm_override
     info "[Generate] primehub.yaml"
     if [[ $PRIMEHUB_MODE == 'ce' ]]; then
-      cp ${DIR}/helmfiles/primehub/helm_override/primehub-ce.yaml $PRIMEHUB_CONFIG
+      cp ${HELMFIEL_PATH}/primehub/helm_override/primehub-ce.yaml $PRIMEHUB_CONFIG
     else
-      cp ${DIR}/helmfiles/primehub/helm_override/primehub-ee.yaml $PRIMEHUB_CONFIG
+      cp ${HELMFIEL_PATH}/primehub/helm_override/primehub-ee.yaml $PRIMEHUB_CONFIG
     fi
   else
     info "[Found] ${PRIMEHUB_CONFIG}"
@@ -930,7 +979,7 @@ install::primehub() {
   progress_primehub &
   BGPID=$!
 
-  helmfile -f ${DIR}/helmfiles/primehub sync || (error_log_primehub; exit 1)
+  helmfile -f ${HELMFIEL_PATH}/primehub sync || (error_log_primehub; exit 1)
 
   info "[Progress] Label nodes with component=singleuser-server"
   kubectl label node component=singleuser-server --overwrite || true
